" ===============================================================
" tender
" A dark and fresh color scheme for vim
" URL: https://github/com/jacoborus/tender.vim
" Author: Jacobo Tabernero http://jacoborus.codes
" License: MIT
" Last Change: 2020/04/24 16:58
" ===============================================================

vim.cmd 'highlight clear'
vim.cmd 'syntax reset'
vim.g.colors_name="tender"

for name, attrs in pairs {
ColorColumn = { bg = #323232 }, 
CursorColumn = { bg = #323232 }, 
CursorLine = { bg = #323232 }, 
CursorLineNr = { fg = #73cef4 }, 
Directory = { fg = #b3deef }, 
DiffAdd = { bg = #464632 }, 
DiffChange = { bg = #335261 }, 
DiffDelete = { fg = #f43753, bg = #79313c }, 
DiffText = { style = { "reverse" } }, 
ErrorMsg = { fg = #f43753, style = { "reverse" } }, 
VertSplit = { fg = #282828, bg = #282828 }, 
Folded = { fg = #666666, bg = #202020 }, 
FoldColumn = { fg = #666666, bg = #202020 },
SignColumn = { fg = #999999, bg = #282828 },
IncSearch = { fg = #ffffff, bg = #000000, style = { "bold", "reverse" } },
LineNr = { fg = #444444 }, 
MatchParen = { fg = #f43753, style = { "bold" } }, 
NonText = { fg = #444444 }, 
Normal = { fg = #eeeeee, bg = #282828 }, 
PMenu = { fg = #dadada, bg = #335261 }, 
PMenuSel = { fg = #335261, bg = #c9d05c }, 
PmenuSbar = { fg = #335261, bg = #335261 }, 
PmenuThumb = { fg = #c9d05c, bg = #c9d05c }, 
Question = { fg = #c9d05c }, 
Search = { fg = #ffffff, style = { "underline", "bold" } },
SpecialKey = { fg = #444444 }, 
SpellBad = { fg = #f43753 }, 
SpellLocal = { fg = #d3b987 }, 
SpellCap = { fg = #ffc24b }, 
SpellRare = { fg = #73cef4 }, 
StatusLine = { fg = #1d1d1d, bg = #666666, style = { "bold" } }, 
StatusLineNC = { fg = #999999, bg = #444444 }, 
TabLine = { fg = #999999, bg = #444444 }, 
TabLineFill = { bg = #444444 }, 
TabLineSel = { fg = #c9d05c, style = { "bold" } }, 
Title = { fg = #b3deef, style = { "bold" } }, 
Visual = { bg = #293b44, style = { "bold" } }, 
VisualNOS = { bg = #293b44, style = { "bold" } }, 
WarningMsg = { fg = #f43753 }, 
WildMenu = { fg = #282828, bg = #c9d05c, style = { "bold" } }, 
Comment = { fg = #666666 }, 
Constant = { fg = #ffc24b }, 
String = { fg = #d3b987 }, 
Character = { fg = #ffc24b }, 
Boolean = { fg = #ffc24b }, 
Number = { fg = #ffc24b }, 
Float = { fg = #ffc24b }, 
Identifier = { fg = #b3deef }, 
Function = { fg = #b3deef }, 
Statement = { fg = #b3deef }, 
Conditional = { fg = #c9d05c }, 
Operator = { fg = #f43753 }, 
Exception = { fg = #f43753 }, 
PreProc = { fg = #c9d05c }, 
Type = { fg = #73cef4 }, 
Special = { fg = #73cef4 }, 
Underlined = { style = { "underline" } }, 
Error = { fg = #eeeeee, bg = #f43753 }, 
Todo = { fg = #f43753, style = { "bold" } }, 
CocErrorSign = { fg = #f43753 }, 
CocWarningSign = { fg = #d3b987 }, 
CocHintSign = { fg = #73cef4 }, 
CocInfoSign = { fg = #ffc24b }, 
cssVendor = { fg = #9faa00 }, 
cssTagName = { fg = #9faa00 }, 
cssAttrComma = { fg = #eeeeee }, 
cssBackgroundProp = { fg = #b3deef }, 
cssBorderProp = { fg = #b3deef }, 
cssBoxProp = { fg = #73cef4 }, 
cssDimensionProp = { fg = #73cef4 }, 
cssFontProp = { fg = #b3deef }, 
cssPositioningProp = { fg = #73cef4 }, 
cssTextProp = { fg = #b3deef }, 
cssValueLength = { fg = #eeeeee }, 
cssValueInteger = { fg = #eeeeee }, 
cssValueNumber = { fg = #eeeeee }, 
cssIdentifier = { fg = #9faa00 }, 
cssIncludeKeyword = { fg = #ffc24b }, 
cssImportant = { fg = #f43753 }, 
cssClassName = { fg = #c9d05c }, 
cssClassNameDot = { fg = #eeeeee }, 
cssProp = { fg = #b3deef }, 
cssAttr = { fg = #eeeeee }, 
cssUnitDecorators = { fg = #eeeeee }, 
cssNoise = { fg = #f43753 }, 
diffRemoved = { fg = #f43753 }, 
diffChanged = { fg = #b3deef }, 
diffAdded = { fg = #c9d05c }, 
diffSubname = { fg = #9faa00 }, 
elmDelimiter = { fg = #eeeeee }, 
elmOperator = { fg = #f43753 }, 
FugitiveblameHash = { fg = #b3deef }, 
FugitiveblameUncommitted = { fg = #f43753 }, 
FugitiveblameTime = { fg = #c9d05c }, 
FugitiveblameNotCommittedYet = { fg = #ffc24b }, 
gitcommitBranch = { fg = #73cef4 }, 
gitcommitDiscardedType = { fg = #c5152f }, 
gitcommitSelectedType = { fg = #9faa00 }, 
gitcommitHeader = { fg = #b3deef }, 
gitcommitUntrackedFile = { fg = #ffc24b }, 
gitcommitDiscardedFile = { fg = #f43753 }, 
gitcommitSelectedFile = { fg = #c9d05c }, 
helpHyperTextEntry = { fg = #c9d05c }, 
helpHeadline = { fg = #73cef4 }, 
helpSectionDelim = { fg = #666666 }, 
helpNote = { fg = #f43753 }, 
javaScriptOperator = { fg = #c9d05c }, 
javaScriptBraces = { fg = #b3deef }, 
javaScriptNull = { fg = #ffc24b }, 
jsonEscape = { fg = #73cef4 }, 
jsonNumber = { fg = #ffc24b }, 
jsonBraces = { fg = #eeeeee }, 
jsonNull = { fg = #ffc24b }, 
jsonBoolean = { fg = #ffc24b }, 
jsonKeywordMatch = { fg = #f43753 }, 
jsonQuote = { fg = #eeeeee }, 
jsonNoise = { fg = #f43753 }, 
markdownH1 = { fg = #b3deef, style = { "bold" } }, 
markdownHeadingRule = { fg = #f43753, style = { "bold" } }, 
markdownHeadingDelimiter = { fg = #f43753, style = { "bold" } }, 
markdownListMarker = { fg = #ffc24b }, 
markdownBlockquote = { fg = #ffc24b }, 
markdownRule = { fg = #c9d05c }, 
markdownLinkText = { fg = #c9d05c }, 
markdownLinkTextDelimiter = { fg = #b3deef }, 
markdownLinkDelimiter = { fg = #b3deef }, 
markdownIdDeclaration = { fg = #9faa00 }, 
markdownAutomaticLink = { fg = #73cef4 }, 
markdownUrl = { fg = #73cef4 }, 
markdownUrlTitle = { fg = #d3b987 }, 
markdownUrlDelimiter = { fg = #ffc24b }, 
markdownUrlTitleDelimiter = { fg = #715b2f }, 
markdownCodeDelimiter = { fg = #73cef4 }, 
markdownCode = { fg = #d3b987 }, 
markdownEscape = { fg = #73cef4 }, 
markdownError = { fg = #f43753 }, 
NERDTreeHelp = { fg = #eeeeee }, 
NERDTreeHelpKey = { fg = #c9d05c }, 
NERDTreeHelpCommand = { fg = #ffc24b }, 
NERDTreeHelpTitle = { fg = #b3deef }, 
NERDTreeUp = { fg = #c9d05c }, 
NERDTreeCWD = { fg = #73cef4 }, 
NERDTreeOpenable = { fg = #f43753 }, 
NERDTreeClosable = { fg = #ffc24b }, 
pugJavascriptOutputChar = { fg = #ffc24b }, 
typescriptParens = { fg = #b3deef }, 
typescriptLogicSymbols = { fg = #f43753 }, 
typescriptReserved = { fg = #73cef4 }, 
typescriptLabel = { fg = #c9d05c }, 
typescriptFuncName = { fg = #c9d05c }, 
typescriptCall = { fg = #ffc24b }, 
typescriptVariable = { fg = #73cef4 }, 
typescriptBinaryOp = { fg = #f43753 }, 
typescriptAssign = { fg = #f43753 }, 
typescriptObjectLabel = { fg = #b3deef }, 
typescriptDotNotation = { fg = #f43753 }, 
typescriptOperator = { fg = #f43753 }, 
typescriptTernaryOp = { fg = #f43753 }, 
typescriptTypeAnnotation = { fg = #f43753 }, 
typescriptIdentifierName = { fg = #eeeeee }, 
typescriptArrowFuncArg = { fg = #ffc24b }, 
typescriptParamImpl = { fg = #ffc24b }, 
typescriptRepeat = { fg = #c9d05c }, 
typescriptStatementKeyword = { fg = #73cef4 }, 
typescriptAliasKeyword = { fg = #c9d05c }, 
typescriptInterfaceKeyword = { fg = #c9d05c }, 
typescriptTemplateSB = { fg = #f43753 }, 
typescriptMemberOptionality = { fg = #ffc24b }, 
typescriptOptionalMark = { fg = #ffc24b }, 
typescriptUnaryOp = { fg = #f43753 }, 
GitGutterAdd = { fg = #c9d05c }, 
GitGutterChange = { fg = #b3deef }, 
GitGutterDelete = { fg = #f43753 }, 
GitGutterChangeDelete = { fg = #f43753 }, 
javaScriptOpSymbols = { fg = #f43753 }, 
javaScriptParens = { fg = #b3deef }, 
javaScriptDocTags = { fg = #6a6b3f }, 
javaScriptDocSeeTag = { fg = #44778d }, 
javaScriptBrowserObjects = { fg = #73cef4 }, 
javaScriptDOMObjects = { fg = #73cef4 }, 
javaScriptFuncArg = { fg = #ffc24b }, 
jsParensIfElse = { fg = #b3deef }, 
jsObjectKey = { fg = #b3deef }, 
jsRepeat = { fg = #c9d05c }, 
jsArrowFunction = { fg = #9faa00 }, 
jsFunctionKey = { fg = #c9d05c }, 
jsFuncName = { fg = #c9d05c }, 
jsObjectFuncName = { fg = #c9d05c }, 
jsNull = { fg = #ffc24b }, 
jsObjectColon = { fg = #f43753 }, 
jsParens = { fg = #b3deef }, 
jsFuncParens = { fg = #b3deef }, 
jsFuncArgs = { fg = #ffc24b }, 
jsSpecial = { fg = #ffc24b }, 
jsTemplateBraces = { fg = #f43753 }, 
jsGlobalObjects = { fg = #73cef4 }, 
jsGlobalNodeObjects = { fg = #b3deef }, 
jsImport = { fg = #73cef4 }, 
jsExport = { fg = #73cef4 }, 
jsExportDefault = { fg = #c9d05c }, 
jsExportDefaultGroup = { fg = #73cef4 }, 
jsFrom = { fg = #73cef4 }, 
plug2 = { fg = #c9d05c }, 
plugH2 = { fg = #73cef4, style = { "bold" } }, 
plugBracket = { fg = #b3deef }, 
plugNumber = { fg = #ffc24b }, 
plugDash = { fg = #ffc24b }, 
plugStar = { fg = #d3b987 }, 
plugMessage = { fg = #ffc24b }, 
plugName = { fg = #b3deef }, 
plugUpdate = { fg = #f43753 }, 
plugEdge = { fg = #c9d05c }, 
plugSha = { fg = #d3b987 }, 
plugNotLoaded = { fg = #79313c }, 
stylusVariable = { fg = #eeeeee }, 
stylusClass = { fg = #c9d05c }, 
stylusClassChar = { fg = #b3deef }, 
stylusId = { fg = #c9d05c }, 
stylusIdChar = { fg = #b3deef }, 
cssVisualVal = { fg = #eeeeee }, 
stylusImport = { fg = #ffc24b }, 
vimCommentString = { fg = #715b2f }, 
vimCommentTitle = { fg = #44778d }, 
vimError = { fg = #eeeeee, bg = #f43753 }, 
xmlNamespace = { fg = #ffc24b }, 
xmlAttribPunct = { fg = #f43753 }, 
xmlProcessingDelim = { fg = #f43753 }, 
javascriptOpSymbol = { fg = #f43753 }, 
javascriptDocNotation = { fg = #6a6b3f }, 
javascriptDocNamedParamType = { fg = #44778d }, 
javascriptDocParamName = { fg = #715b2f }, 
javascriptDocParamType = { fg = #44778d }, 
javascriptTemplateSB = { fg = #f43753 }, 
javascriptRepeat = { fg = #c9d05c }, 
javascriptObjectLabelColon = { fg = #f43753 }, 
javascriptObjectMethodName = { fg = #c9d05c }, 
javascriptFuncName = { fg = #c9d05c }, 
yamlFlowString = { fg = #d3b987 }, 
yamlFlowStringDelimiter = { fg = #eeeeee }, 
yamlKeyValueDelimiter = { fg = #f43753 }, 
} do
  if type(attrs) == 'table' then
    vim.api.nvim_set_hl(0, name, attrs)
  else
    vim.api.nvim_set_hl(0, name, { link = attrs })
  end
end

hi link SignifySignAdd GitGutterAdd
hi link SignifySignDelete GitGutterDelete
hi link SignifySignDeleteFirstLine SignifySignDelete
hi link SignifySignChange GitGutterChange
hi link SignifySignChangeDelete GitGutterChangeDelete

vim.g.terminal_color_foreground = "#282828"
vim.g.terminal_color_background = "#eeeeee"
vim.g.terminal_color_0 = "#282828"
vim.g.terminal_color_1 = "#f43753"
vim.g.terminal_color_2 = "#c9d05c"
vim.g.terminal_color_3 = "#ffc24b"
vim.g.terminal_color_4 = "#b3deef"
vim.g.terminal_color_5 = "#d3b987"
vim.g.terminal_color_6 = "#73cef4"
vim.g.terminal_color_7 = "#eeeeee"
vim.g.terminal_color_8 = "#1d1d1d"
vim.g.terminal_color_9 = "#f43753"
vim.g.terminal_color_10 = "#c9d05c"
vim.g.terminal_color_11 = "#ffc24b"
vim.g.terminal_color_12 = "#b3deef"
vim.g.terminal_color_13 = "#d3b987"
vim.g.terminal_color_14 = "#73cef4"
vim.g.terminal_color_15 = "#ffffff"

" ===================================
" Generated by Estilo 1.4.1
" https://github.com/jacoborus/estilo
" ===================================
